In [2]:
import sys
sys.path.append('../..')

from ml_imports import *

In [3]:
!pip install skimage

Collecting skimage
  Using cached skimage-0.0.tar.gz (757 bytes)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]

      *** Please install the `scikit-image` package (instead of `skimage`) ***

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'skimage' when getting requirements to build wheel

In [4]:
import os
from sklearn.svm import SVC
from skimage.io import imread #to read img
from skimage.transform import resize #to resize image

In [5]:
os.listdir("D:\desktop\luminar\Deep Learning\CNN\ML_Image_classifi\Data")

['Cat', 'Dog']

In [6]:
os.listdir("D:\desktop\luminar\Deep Learning\CNN\ML_Image_classifi\Data\cat")

['cat.100.jpg',
 'cat.101.jpg',
 'cat.102.jpg',
 'cat.103.jpg',
 'cat.104.jpg',
 'cat.105.jpg',
 'cat.106.jpg',
 'cat.107.jpg',
 'cat.108.jpg',
 'cat.109.jpg',
 'cat.110.jpg',
 'cat.111.jpg',
 'cat.112.jpg',
 'cat.113.jpg',
 'cat.114.jpg',
 'cat.115.jpg',
 'cat.116.jpg',
 'cat.117.jpg',
 'cat.118.jpg',
 'cat.119.jpg',
 'cat.35.jpg',
 'cat.36.jpg',
 'cat.37.jpg',
 'cat.38.jpg',
 'cat.39.jpg',
 'cat.40.jpg',
 'cat.41.jpg',
 'cat.42.jpg',
 'cat.43.jpg',
 'cat.44.jpg',
 'cat.45.jpg',
 'cat.46.jpg',
 'cat.47.jpg',
 'cat.48.jpg',
 'cat.49.jpg',
 'cat.50.jpg',
 'cat.51.jpg',
 'cat.52.jpg',
 'cat.53.jpg',
 'cat.54.jpg',
 'cat.55.jpg',
 'cat.56.jpg',
 'cat.57.jpg',
 'cat.58.jpg',
 'cat.59.jpg',
 'cat.60.jpg',
 'cat.61.jpg',
 'cat.62.jpg',
 'cat.63.jpg',
 'cat.64.jpg',
 'cat.65.jpg',
 'cat.66.jpg',
 'cat.67.jpg',
 'cat.68.jpg',
 'cat.69.jpg',
 'cat.70.jpg',
 'cat.71.jpg',
 'cat.72.jpg',
 'cat.73.jpg',
 'cat.74.jpg',
 'cat.75.jpg',
 'cat.76.jpg',
 'cat.77.jpg',
 'cat.78.jpg',
 'cat.79.jpg',
 'cat.80.jpg',
 'cat.81.jpg',
 'cat.82.jpg',
 'cat.83.jpg',
 'cat.84.jpg',
 'cat.85.jpg',
 'cat.86.jpg',
 'cat.87.jpg',
 'cat.88.jpg',
 'cat.89.jpg',
 'cat.90.jpg',
 'cat.91.jpg',
 'cat.92.jpg',
 'cat.93.jpg',
 'cat.94.jpg',
 'cat.95.jpg',
 'cat.96.jpg',
 'cat.97.jpg',
 'cat.98.jpg',
 'cat.99.jpg']

In [7]:
len(os.listdir("D:\desktop\luminar\Deep Learning\CNN\ML_Image_classifi\Data\dog"))

68

In [8]:
#path join

catpath = os.path.join("D:\desktop\luminar\Deep Learning\CNN\ML_Image_classifi\Data",'cat')
for i in os.listdir(catpath):
    print(i)

cat.100.jpg
cat.101.jpg
cat.102.jpg
cat.103.jpg
cat.104.jpg
cat.105.jpg
cat.106.jpg
cat.107.jpg
cat.108.jpg
cat.109.jpg
cat.110.jpg
cat.111.jpg
cat.112.jpg
cat.113.jpg
cat.114.jpg
cat.115.jpg
cat.116.jpg
cat.117.jpg
cat.118.jpg
cat.119.jpg
cat.35.jpg
cat.36.jpg
cat.37.jpg
cat.38.jpg
cat.39.jpg
cat.40.jpg
cat.41.jpg
cat.42.jpg
cat.43.jpg
cat.44.jpg
cat.45.jpg
cat.46.jpg
cat.47.jpg
cat.48.jpg
cat.49.jpg
cat.50.jpg
cat.51.jpg
cat.52.jpg
cat.53.jpg
cat.54.jpg
cat.55.jpg
cat.56.jpg
cat.57.jpg
cat.58.jpg
cat.59.jpg
cat.60.jpg
cat.61.jpg
cat.62.jpg
cat.63.jpg
cat.64.jpg
cat.65.jpg
cat.66.jpg
cat.67.jpg
cat.68.jpg
cat.69.jpg
cat.70.jpg
cat.71.jpg
cat.72.jpg
cat.73.jpg
cat.74.jpg
cat.75.jpg
cat.76.jpg
cat.77.jpg
cat.78.jpg
cat.79.jpg
cat.80.jpg
cat.81.jpg
cat.82.jpg
cat.83.jpg
cat.84.jpg
cat.85.jpg
cat.86.jpg
cat.87.jpg
cat.88.jpg
cat.89.jpg
cat.90.jpg
cat.91.jpg
cat.92.jpg
cat.93.jpg
cat.94.jpg
cat.95.jpg
cat.96.jpg
cat.97.jpg
cat.98.jpg
cat.99.jpg

In [9]:
#path join

dogpath = os.path.join("D:\desktop\luminar\Deep Learning\CNN\ML_Image_classifi\Data",'dog')
for i in os.listdir(dogpath):
    print(i)

dog.1.jpg
dog.10.jpg
dog.11.jpg
dog.12.jpg
dog.13.jpg
dog.14.jpg
dog.15.jpg
dog.16.jpg
dog.17.jpg
dog.18.jpg
dog.19.jpg
dog.2.jpg
dog.20.jpg
dog.21.jpg
dog.22.jpg
dog.23.jpg
dog.24.jpg
dog.25.jpg
dog.26.jpg
dog.27.jpg
dog.28.jpg
dog.29.jpg
dog.3.jpg
dog.30.jpg
dog.31.jpg
dog.32.jpg
dog.33.jpg
dog.34.jpg
dog.35.jpg
dog.36.jpg
dog.37.jpg
dog.38.jpg
dog.39.jpg
dog.4.jpg
dog.40.jpg
dog.41.jpg
dog.42.jpg
dog.43.jpg
dog.44.jpg
dog.45.jpg
dog.46.jpg
dog.47.jpg
dog.48.jpg
dog.49.jpg
dog.5.jpg
dog.50.jpg
dog.51.jpg
dog.52.jpg
dog.53.jpg
dog.54.jpg
dog.55.jpg
dog.56.jpg
dog.57.jpg
dog.58.jpg
dog.59.jpg
dog.6.jpg
dog.60.jpg
dog.61.jpg
dog.62.jpg
dog.63.jpg
dog.64.jpg
dog.65.jpg
dog.66.jpg
dog.67.jpg
dog.68.jpg
dog.7.jpg
dog.8.jpg
dog.9.jpg

In [10]:
flat_data_arr=[] # to collect input
target_arr=[] # to collect output

categories=['cat','dog']

data_dir='D:\desktop\luminar\Deep Learning\CNN\ML_Image_classifi\Data'

In [11]:
#core
for i in categories:
    print(f" Loading {i} categories.........")
    path=os.path.join(data_dir,i)
    for img in os.listdir(path):
        img_arr=imread(os.path.join(path,img))
        img_resize=resize(img_arr,(150,150,3))
        flat_data_arr.append(img_resize.flatten())
        target_arr.append(categories.index(i))
    print("Loaded complete",i)

 Loading cat categories.........
Loaded complete cat
 Loading dog categories.........
Loaded complete dog

In [12]:
flat_data=np.array(flat_data_arr)
target_data=np.array(target_arr)

In [13]:
df=pd.DataFrame(flat_data)
df

,0,1,2,3,4,5,6,7,8,9,...,67490,67491,67492,67493,67494,67495,67496,67497,67498,67499
0,0.869272,0.873193,0.853585,0.873435,0.877356,0.857749,0.875278,0.879199,0.859591,0.869854,...,0.850214,0.838799,0.828248,0.816542,0.845064,0.832109,0.811390,0.850880,0.828851,0.824736
1,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281569,...,0.975382,0.677381,0.997971,0.993252,0.674711,0.988845,0.975943,0.709319,0.992365,0.986100
2,0.567769,0.512867,0.461886,0.573767,0.518865,0.467885,0.545760,0.490858,0.439877,0.557858,...,0.521950,0.728231,0.660557,0.600644,0.698120,0.629841,0.567903,0.732229,0.653866,0.600209
3,0.601961,0.617647,0.613726,0.604402,0.620088,0.616167,0.597635,0.613321,0.609399,0.596407,...,0.680711,0.632742,0.635138,0.645287,0.631576,0.633479,0.642293,0.690567,0.689876,0.689292
4,0.521881,0.553253,0.470901,0.420852,0.452224,0.369871,0.449323,0.480696,0.398343,0.442058,...,0.717869,0.845957,0.571443,0.706927,0.823215,0.559962,0.691698,0.885277,0.622532,0.754099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0.567795,0.743022,0.536629,0.576316,0.754119,0.562781,0.532521,0.711565,0.525503,0.521763,...,0.192060,0.292546,0.214115,0.210193,0.233386,0.154954,0.151033,0.266417,0.187986,0.184064
149,0.339050,0.367841,0.423704,0.496663,0.514714,0.548421,0.471958,0.488760,0.506873,0.425741,...,0.305655,0.616179,0.447552,0.310297,0.623240,0.454612,0.317357,0.612691,0.444063,0.306808
150,0.078935,0.086778,0.075013,0.082741,0.090585,0.078820,0.097564,0.105407,0.093643,0.116938,...,0.505489,0.518806,0.530571,0.550179,0.496733,0.508497,0.528105,0.494269,0.506033,0.525641
151,0.342631,0.439104,0.279701,0.275549,0.388488,0.238657,0.286709,0.418971,0.200387,0.280261,...,0.972995,0.987786,0.964669,0.972176,0.988084,0.964348,0.967420,0.984593,0.961269,0.961172
152,0.815650,0.849131,0.845227,0.933889,0.955618,0.969236,0.891768,0.905157,0.937564,0.477821,...,0.094129,0.313858,0.429106,0.209400,0.405920,0.508851,0.307331,0.362543,0.453008,0.271112

In [14]:
df.shape[0]

153

In [15]:
df['target']=target_data
df

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,target
0,0.869272,0.873193,0.853585,0.873435,0.877356,0.857749,0.875278,0.879199,0.859591,0.869854,...,0.838799,0.828248,0.816542,0.845064,0.832109,0.811390,0.850880,0.828851,0.824736,0
1,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281699,0.995425,0.999346,0.281569,...,0.677381,0.997971,0.993252,0.674711,0.988845,0.975943,0.709319,0.992365,0.986100,0
2,0.567769,0.512867,0.461886,0.573767,0.518865,0.467885,0.545760,0.490858,0.439877,0.557858,...,0.728231,0.660557,0.600644,0.698120,0.629841,0.567903,0.732229,0.653866,0.600209,0
3,0.601961,0.617647,0.613726,0.604402,0.620088,0.616167,0.597635,0.613321,0.609399,0.596407,...,0.632742,0.635138,0.645287,0.631576,0.633479,0.642293,0.690567,0.689876,0.689292,0
4,0.521881,0.553253,0.470901,0.420852,0.452224,0.369871,0.449323,0.480696,0.398343,0.442058,...,0.845957,0.571443,0.706927,0.823215,0.559962,0.691698,0.885277,0.622532,0.754099,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0.567795,0.743022,0.536629,0.576316,0.754119,0.562781,0.532521,0.711565,0.525503,0.521763,...,0.292546,0.214115,0.210193,0.233386,0.154954,0.151033,0.266417,0.187986,0.184064,1
149,0.339050,0.367841,0.423704,0.496663,0.514714,0.548421,0.471958,0.488760,0.506873,0.425741,...,0.616179,0.447552,0.310297,0.623240,0.454612,0.317357,0.612691,0.444063,0.306808,1
150,0.078935,0.086778,0.075013,0.082741,0.090585,0.078820,0.097564,0.105407,0.093643,0.116938,...,0.518806,0.530571,0.550179,0.496733,0.508497,0.528105,0.494269,0.506033,0.525641,1
151,0.342631,0.439104,0.279701,0.275549,0.388488,0.238657,0.286709,0.418971,0.200387,0.280261,...,0.987786,0.964669,0.972176,0.988084,0.964348,0.967420,0.984593,0.961269,0.961172,1
152,0.815650,0.849131,0.845227,0.933889,0.955618,0.969236,0.891768,0.905157,0.937564,0.477821,...,0.313858,0.429106,0.209400,0.405920,0.508851,0.307331,0.362543,0.453008,0.271112,1

In [16]:
#svm
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0])

In [20]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.6451612903225806

In [21]:
path1='D:/desktop/luminar/Deep Learning/CNN/ML_Image_classifi/test_cat.webp'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])